### ISSUE TITLE
WifiConnect not working on pi4 at version `2.53.12+rev1`

### ISSUE THREAD

**Issue by floion** [balena-os/balena-raspberrypi#522] opened 2020-08-06 09:59 UTC
06.08.20 10:59:27 (+0300)  main  Starting WiFi Connect
06.08.20 10:59:27 (+0300)  main  WiFi device: wlan0
06.08.20 10:59:27 (+0300)  main  Access points: ["DIRECT-D2-HP DeskJet 4530 series", "Balena", "Balena5GHz", "dlink", "ALINA", "TP-LINK_2D5A", "supVG", "ZyXEL_SSID3"]
06.08.20 10:59:27 (+0300)  main  Starting access point...
06.08.20 10:59:29 (+0300)  main  Access point 'WiFi Connect' created
06.08.20 10:59:29 (+0300)  main  Starting HTTP server on 192.168.42.1:80
06.08.20 10:59:47 (+0300)  main  User connected to the captive portal
06.08.20 11:00:07 (+0300)  main  Stopping access point 'WiFi Connect'...
06.08.20 11:00:09 (+0300)  main  Access point 'WiFi Connect' stopped
06.08.20 11:00:11 (+0300)  main  Access points: ["DIRECT-D2-HP DeskJet 4530 series", "Balena", "Balena5GHz", "dlink", "TP-LINK_2D5A", "supVG"]
06.08.20 11:00:11 (+0300)  main  Connecting to access point 'Balena'...
06.08.20 11:00:27 (+0300)  main  [wifi_connect::network:WARN] Connection to access point not activated 'Balena': Activating
06.08.20 11:00:27 (+0300)  main  Error: Getting access points failed
06.08.20 11:00:27 (+0300)  main    caused by: D-Bus failure: Get org.freedesktop.NetworkManager.AccessPoint::WpaFlags property failed on /org/freedesktop/NetworkManager/AccessPoint/20: No such interface “org.freedesktop.DBus.Properties” on object at path /org/freedesktop/NetworkManager/AccessPoint/20
06.08.20 11:00:27 (+0300)  main    caused by: "No such interface “org.freedesktop.DBus.Properties” on object at path /org/freedesktop/NetworkManager/AccessPoint/20"

**Comment by acostach** [comment] 2020-12-18 13:41
Closing this @floion based on the 2.65.0+rev1 Pi4 test run results. Please re-open if the issue is still present.

**Closed by acostach** 2020-12-18 13:41 UTC
