### ISSUE TITLE
build error: do_overlays()

### ISSUE THREAD

**Issue by delhiryder** [balena-os/balena-raspberrypi#1055] opened 2023-08-08 13:56 UTC
I am attempting to build the raspberrypi4-64 MACHINE on an Ubuntu 22.04 machine. Tried to run both the 'barys' and 'balena_build.sh' scripts, and they're both failing at the same place (see error message below):

ERROR: linux-raspberrypi-1_5.15.92+gitAUTOINC+e1b976ee4f_14b35093ca-r0 do_compile: Error executing a python function in exec_func_python() autogenerated:

The stack trace of python calls that resulted in this exception/failure was:
File: 'exec_func_python() autogenerated', lineno: 2, function: <module>
     0001:
 *** 0002:do_overlays(d)
     0003:
File: '/work/build/../layers/meta-balena-raspberrypi/recipes-kernel/linux/linux-raspberrypi_%.bbappend', lineno: 24, function: do_overlays
     0020:        overlays.append(re.sub(r'-overlay.dts','.dtbo',overlay).split('dts/')[-1])
     0021:    for dtbo in overlays:
     0022:        d.setVar('KERNEL_DEVICETREE', d.getVar('KERNEL_DEVICETREE', True) + ' ' + dtbo)
     0023:
 *** 0024:    f = open(d.getVar('DEPLOY_DIR_IMAGE') + '/overlays.txt', "w")
     0025:    f.write(d.getVar('KERNEL_DEVICETREE', True))
     0026:    f.close
     0027:}
     0028:
Exception: FileNotFoundError: [Errno 2] No such file or directory: '/work/build/tmp/deploy/images/raspberrypi4-64/overlays.txt'

Should I be on another branch (or a different commit/tag). I am especially interested in using kirkstone compatible layers (and this repo seems to be the most up to date).
Thanks,
Sidd

**Comment by delhiryder** [comment] 2023-08-08 20:45
Quick update: I was able to get past this error by making the directory in question: 

mkdir -p /work/build/tmp/deploy/images/raspberrypi4-64/

and restarting the build. Obviously not a permanent fix, but maybe something to help diagnose the issue ?

**Comment by alexgg** [comment] 2023-08-16 07:57
hi @delhiryder I am using `Ubuntu 22.04.2 LTS (Jammy Jellyfish)` natively and the current master branch of the `balena-raspberrypi` repository builds without issues.
Could you please try to `bitbake -c cleanall virtual/kernel` and try again?

**Comment by alexgg** [comment] 2023-08-16 07:57
Can't reproduce.

**Comment by majorz** [comment] 2023-09-22 16:57
I've run into this on a clean build as well:

```
ERROR: linux-raspberrypi-1_5.15.92+gitAUTOINC+e1b976ee4f_14b35093ca-r0 do_compile: Error executing a python function in exec_func_python() autogenerated:

The stack trace of python calls that resulted in this exception/failure was:
File: 'exec_func_python() autogenerated', lineno: 2, function: <module>
     0001:
 *** 0002:do_overlays(d)
     0003:
File: '/home/majorz/balena-raspberrypi/build/../layers/meta-balena-raspberrypi/recipes-kernel/linux/linux-raspberrypi_%.bbappend', lineno: 24, function: do_overlays
     0020:        overlays.append(re.sub(r'-overlay.dts','.dtbo',overlay).split('dts/')[-1])
     0021:    for dtbo in overlays:
     0022:        d.setVar('KERNEL_DEVICETREE', d.getVar('KERNEL_DEVICETREE', True) + ' ' + dtbo)
     0023:
 *** 0024:    f = open(d.getVar('DEPLOY_DIR_IMAGE') + '/overlays.txt', "w")
     0025:    f.write(d.getVar('KERNEL_DEVICETREE', True))
     0026:    f.close
     0027:}
     0028:
Exception: FileNotFoundError: [Errno 2] No such file or directory: '/home/majorz/balena-raspberrypi/build/tmp/deploy/images/raspberrypicm4-ioboard/overlays.txt'

ERROR: Logfile of failure stored in: /home/majorz/balena-raspberrypi/build/tmp/work/raspberrypicm4_ioboard-poky-linux/linux-raspberrypi/1_5.15.92+gitAUTOINC+e1b976ee4f_14b35093ca-r0/temp/log.do_compile.907269
ERROR: Task (/home/majorz/balena-raspberrypi/build/../layers/meta-raspberrypi/recipes-kernel/linux/linux-raspberrypi_5.15.bb:do_compile) failed with exit code '1'
```

**Comment by floion** [comment] 2024-02-29 14:27
Should be fixed by https://github.com/balena-os/balena-raspberrypi/pull/1105

**Closed by floion** 2024-02-29 14:27 UTC
